### PR TITLE
Add a printer drawing widget to our printing page

### PR DESCRIPTION
**Pull request by lazyatom**
This is an extraction of the code from the printer paint application and printer sample HTML pages, stripped down to make it work in an embedded context and without a database to store data.

The basic premise is that once the drawing is ready to send, we extract the hidden "picture" element and send just that HTML to the printer server.

Note: something about this is stopping my printer from actually printing this data. Despite the picture appearing happily in the print archive, the data that gets downloaded is only 13 bytes. There must be something weird in the data itself. HMMM.

### CODE REVIEW

**Comment by lazyatom** [comment]
> We should be giving people feedback on what controls are selected. I've added a .selected style to the control buttons as you can see, but I don't know how to make that work properly.

This is done

**Comment by lazyatom** [comment]
> I've added required="required" to the From input field

This doesn't work because we don't actually use form submission to send the printer data . I've changed the implementation to watch for form submssion rather than button clicking, and now it works 👍

**Comment by mlettini** [comment]
Thanks @lazyatom! I made a few tweaks to how this page fits into the rest of GE, linking it on Contact, and I think it's good to go IMO.

**Comment by lazyatom** [comment]
I've merged this, but I think still pending is re-creating it under /guestbook

**Pull request merged**
